/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class fr_myrddin_clipper_Clipper */

#ifndef _Included_fr_myrddin_clipper_Clipper
#define _Included_fr_myrddin_clipper_Clipper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_myrddin_clipper_Clipper
 * Method:    jniClipPolygon
 * Signature: ([II[IIIII)V
 */
JNIEXPORT jobjectArray JNICALL Java_fr_myrddin_clipper_Clipper_jniClipPolygon
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
