/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class fr_myrddin_clipper_Clipper */

#ifndef _Included_fr_myrddin_clipper_Clipper
#define _Included_fr_myrddin_clipper_Clipper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_myrddin_clipper_Clipper
 * Method:    jniClipPolygon
 * Signature: ([II[IIIII)V
 */
JNIEXPORT jobjectArray JNICALL Java_fr_myrddin_clipper_Clipper_jniClipPolygon
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint);
  
JNIEXPORT jobjectArray JNICALL Java_fr_myrddin_clipper_Clipper_jniExecute
  (JNIEnv *, jobject, jlong, jint, jint, jint);
  
JNIEXPORT jboolean JNICALL Java_fr_myrddin_clipper_Clipper_jniAddSubject
  (JNIEnv *, jobject, jlong, jdoubleArray);
  
JNIEXPORT jboolean JNICALL Java_fr_myrddin_clipper_Clipper_jniAddClip
  (JNIEnv *, jobject, jlong, jdoubleArray);
  
JNIEXPORT jlong JNICALL Java_fr_myrddin_clipper_Clipper_jniNewClipper
  (JNIEnv *, jobject);
  
JNIEXPORT void JNICALL Java_fr_myrddin_clipper_Clipper_jniDispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
